// AUTO-GENERATED by scripts/build-skill-filter.js — do not edit manually
// Run: node scripts/build-skill-filter.js
const fs = require('fs');
const path = require('path');

const CLASSIC_ONLY = new Set(["add-action","add-adaptive-card","add-generative-answers","add-global-variable","add-knowledge","add-node","add-other-agents","edit-action","edit-agent","edit-triggers","list-topics","new-topic"]);
const MODERN_ONLY = new Set(["edit-agent-modern","list-skills","new-skill"]);

function detectAgentType(cwd) {
  function findSettings(dir, depth) {
    if (depth > 4) return null;
    try {
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const e of entries) {
        if (e.name === 'settings.mcs.yml' && e.isFile()) return path.join(dir, e.name);
      }
      for (const e of entries) {
        if (e.isDirectory() && !e.name.startsWith('.') && e.name !== 'node_modules') {
          const found = findSettings(path.join(dir, e.name), depth + 1);
          if (found) return found;
        }
      }
    } catch {}
    return null;
  }

  const settingsPath = findSettings(cwd, 0);
  if (!settingsPath) return '';

  const content = fs.readFileSync(settingsPath, 'utf8');
  if (/template:\s*cliagent-/.test(content) ||
      /\$kind:\s*CLICopilotRecognizer/.test(content) ||
      /kind:\s*CLICopilotRecognizer/.test(content) ||
      /kind:\s*CLIAgentRecognizer/.test(content)) {
    return 'modern';
  }
  return 'classic';
}

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  try {
    const data = JSON.parse(input);
    const skillField = (data.tool_input && data.tool_input.skill) || '';
    const command = skillField.includes(':') ? skillField.split(':').pop() : skillField;
    if (!command) process.exit(0);

    const cwd = data.cwd || process.cwd();
    const agentType = detectAgentType(cwd);
    if (!agentType) process.exit(0);

    const blocked = agentType === 'modern' ? CLASSIC_ONLY : MODERN_ONLY;
    if (blocked.has(command)) {
      const opposite = agentType === 'modern' ? 'classic' : 'modern';
      process.stdout.write(JSON.stringify({
        decision: 'block',
        reason: 'The "' + command + '" skill is for ' + opposite + ' agents only. This workspace contains a ' + agentType + ' agent.'
      }));
    }
  } catch {}
});
